language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction

env:
  global:
    - DEFAULT=1

script:
  - vendor/bin/phpunit --coverage-text --exclude-group integration

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0

  allow_failures:
    - env: CODECOVERAGE=1 DEFAULT=0

notifications:
  email: false
